#!/usr/bin/env bash
set -euo pipefail

cd "$(dirname "$0")"

say()  { printf '\033[1;36m==>\033[0m %s\n' "$*"; }
warn() { printf '\033[1;33m!! \033[0m %s\n' "$*" >&2; }
die()  { printf '\033[1;31mxx \033[0m %s\n' "$*" >&2; exit 1; }

need() {
  command -v "$1" >/dev/null 2>&1 || die "missing dependency: $1 — please install it and re-run ./setup.sh"
}

say "Checking required tools"
need node
need npm
need python3
need openssl

node_major=$(node -p 'process.versions.node.split(".")[0]')
[[ "$node_major" -ge 18 ]] || die "node >= 18 required (found $(node -v))"

py_ok=$(python3 -c 'import sys; print(1 if sys.version_info >= (3,11) else 0)')
[[ "$py_ok" == "1" ]] || die "python3 >= 3.11 required (found $(python3 -V))"

if [[ -d node_modules ]]; then
  say "node_modules present — skipping npm install (delete it to force reinstall)"
else
  say "Installing npm dependencies"
  npm install
fi

if [[ -x .venv/bin/python ]]; then
  say ".venv present — skipping venv creation"
else
  say "Creating Python virtualenv at .venv"
  python3 -m venv .venv
fi

say "Installing Python dependencies"
.venv/bin/pip install --quiet --upgrade pip
.venv/bin/pip install --quiet -r requirements.txt

if [[ -f .env.local ]]; then
  say ".env.local already present — leaving it untouched"
else
  say "Generating .env.local"
  internal_key=$(openssl rand -hex 32)

  printf '\n'
  read -rp "Paste your Supabase DATABASE_URL (postgresql://...?sslmode=require): " db_url
  if [[ -z "$db_url" ]]; then
    warn "DATABASE_URL left empty — fill it in .env.local before running ./run.sh"
    db_url="postgresql://USER:PASSWORD@HOST:6543/postgres?sslmode=require"
  fi

  tmp=$(mktemp)
  cat >"$tmp" <<EOF
# Generated by setup.sh — safe to edit, do not commit.
INTERNAL_API_KEY=$internal_key
INTERNAL_API_URL=http://127.0.0.1:3000
DATABASE_URL=$db_url
EOF
  mv "$tmp" .env.local
  chmod 600 .env.local
  say "Wrote .env.local (chmod 600)"
fi

if [[ -f sql/schema.sql ]]; then
  printf '\n'
  read -rp "Apply sql/schema.sql to your database now? [y/N] " apply
  if [[ "${apply:-}" =~ ^[Yy]$ ]]; then
    if command -v psql >/dev/null 2>&1; then
      # shellcheck disable=SC1091
      set -a; source .env.local; set +a
      psql "$DATABASE_URL" -f sql/schema.sql
    else
      warn "psql not found — apply manually: psql \"\$DATABASE_URL\" -f sql/schema.sql"
    fi
  fi
fi

printf '\n'
say "Setup complete. Run ./run.sh to start the app."
